apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config
  labels:
    app: sonarr
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/k8s/sonarr-config
    server: san.explorer
