apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nextcloud-mariadb-0
  labels:
    app: nextcloud
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/k8s/nextcloud/mariadb
    server: san.explorer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-apache
  labels:
    app: nextcloud
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/k8s/nextcloud/html
    server: san.explorer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
  labels:
    app: nextcloud
spec:
  capacity:
    storage: 48Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/k8s/nextcloud/data
    server: san.explorer
