apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-gitlab-ee-pgsql
  labels:
    app: gitlab-gitlab-ee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-gitlab-ee-redis
  labels:
    app: gitlab-gitlab-ee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
