apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "serviio.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "serviio.name" . }}
    helm.sh/chart: {{ include "serviio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "serviio.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "serviio.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: serviio.boundAddr
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
{{ toYaml .Values.env | indent 12 }}
          ports:
            - name: console
              containerPort: 23423
              protocol: TCP
            - name: browser
              containerPort: 23424
              protocol: TCP
            - name: webserver
              containerPort: 8895
              protocol: TCP
            - name: upnp
              containerPort: 1900
              protocol: UDP
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: serviio-data
            subPath: config
            mountPath: /opt/serviio/config
          - name: serviio-data
            subPath: library
            mountPath: /opt/serviio/library
          - name: serviio-data
            subPath: plugins
            mountPath: /opt/serviio/plugins
          - name: serviio-data
            subPath: log
            mountPath: /opt/serviio/log
          - name: serviio-movies
            mountPath: /media/serviio
          - name: serviio-transcode
            mountPath: /var/serviio
      volumes:
      - name: serviio-data
        persistentVolumeClaim:
          claimName: serviio-data
      - name: serviio-movies
        persistentVolumeClaim:
          claimName: lib-movies
      - name: serviio-transcode
        persistentVolumeClaim:
          claimName: transcode
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
