apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "serviio.fullname" . }}
  labels:
    app: {{ template "serviio.name" . }}
    chart: {{ template "serviio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "serviio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "serviio.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{ toYaml .Values.env | indent 12 }}
          ports:
            - name: console
              containerPort: 23423
              protocol: TCP
            - name: browser
              containerPort: 23424
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: serviio-config
            mountPath: /config
          - name: serviio-movies
            mountPath: /media/video
          - name: serviio-pictures
            mountPath: /media/pictures
          - name: serviio-transcode
            mountPath: /transcode
      volumes:
      - name: serviio-config
        persistentVolumeClaim:
          claimName: serviio-config
      - name: serviio-movies
        persistentVolumeClaim:
          claimName: lib-movies
      - name: serviio-pictures
        persistentVolumeClaim:
          claimName: lib-pictures
      - name: serviio-transcode
        persistentVolumeClaim:
          claimName: transcode
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
