apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "serviio.fullname" . }}-config
  labels:
    app: {{ template "serviio.name" . }}
    chart: {{ template "serviio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: {{ .Values.persistence.config.path }}
    server: {{ .Values.persistence.config.server }}

