apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "serviio.fullname" . }}-data
  labels:
    app.kubernetes.io/name: {{ include "serviio.name" . }}
    helm.sh/chart: {{ include "serviio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: {{ .Values.persistence.data.path }}
    server: {{ .Values.persistence.data.server }}

