apiVersion: v1
kind: Service
metadata:
  name: {{ template "serviio.fullname" . }}-console
  labels:
    app.kubernetes.io/name: {{ include "serviio.name" . }}
    helm.sh/chart: {{ include "serviio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 23423
      targetPort: console
      protocol: TCP
      name: console
  selector:
    app.kubernetes.io/name: {{ include "serviio.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "serviio.fullname" . }}-browser
  labels:
    app.kubernetes.io/name: {{ include "serviio.name" . }}
    helm.sh/chart: {{ include "serviio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 23424
      targetPort: browser
      protocol: TCP
      name: browser
  selector:
    app.kubernetes.io/name: {{ include "serviio.name" . }}
