apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
  labels:
    app: plex
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /fastdata/k8s/plex-config
    server: 172.16.0.10
