plexClaim: "claim-o7MyPRyywc4AjsRM-Fps"
changeConfigDirOwnership: false
plexGid: 10
plexUid: 200
allowedNetworks:  "10.244.0.0/16"

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/issuer: ca-kubernetes-issuer
  path: /
  hosts:
    - plex.explorer
  tls:
    - secretName: plex-tls
      hosts:
        - plex.explorer

resources:
  limits:
    gpu.intel.com/i915: 1
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 768Mi

nodeSelector: {
  gpu-node: "true"
}

persistence:
  transcode:
    enabled: true
    size: 5Gi
    claimName: transcode
  data:
    size: 6Ti
    claimName: lib-media
  config:
    size: 2Gi
    claimName: plex-config
