apiVersion: v1
kind: PersistentVolume
metadata:
  name: sickchill-config
  labels:
    app: sickchill
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/k8s/sickrage-config
    server: san.explorer
