kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-{{ template "gitlab.fullname" . }}-ssh
  labels:
    app: {{ template "gitlab.name" . }}-tcp
    chart: {{ template "gitlab.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  8889: default/{{ template "gitlab.fullname" . }}:ssh
