{{ if (.Values.gitlabOmnibusConfiguration) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gitlab.name" . }}
    helm.sh/chart: {{ include "gitlab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  GITLAB_OMNIBUS_CONFIG: |
{{ .Values.gitlabOmnibusConfiguration | indent 4 }}
{{- if .Values.postgresql.enabled}}
  ## DB configuration
  ##
  DB_HOST: {{ template "gitlab.postgresql.fullname" . }}
  DB_USER: {{ .Values.postgresql.postgresqlUsername | quote }}
  DB_DATABASE: {{ .Values.postgresql.postgresqlDatabase | quote }}
{{- end }}
{{- if .Values.redis.enabled}}
  ## Redis configuration
  ##
  REDIS_HOST: {{ template "gitlab.redis.fullname" . }}-master
  {{- end }}
{{ end }}
