{{ if (.Values.gitlabOmnibusConfiguration) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gitlab.name" . }}
    helm.sh/chart: {{ include "gitlab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  GITLAB_OMNIBUS_CONFIG: |
{{ .Values.gitlabOmnibusConfiguration | indent 4 }}
  ## DB configuration
  ##
  DB_HOST: {{ template "gitlab.postgresql.fullname" . }}
  DB_USER: {{ .Values.postgresql.postgresUsername | quote }}
  DB_DATABASE: {{ .Values.postgresql.postgresqlDatabase | quote }}
  ## Redis configuration
  ##
  REDIS_HOST: {{ template "gitlab.redis.fullname" . }}
{{ end }}
