apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gitlab.name" . }}
    helm.sh/chart: {{ include "gitlab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gitlab.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gitlab.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: ssh
            containerPort: 22
          - name: http
            containerPort: 80
          envFrom:
            configMapRef:
              - name: {{ template "gitlab.fullname" . }}
{{ toYaml .Values.env | indent 12 }}
          livenessProbe:
            httpGet:
              path: /help
              port: {{ .Values.livenessPort }}
            # This pod takes a very long time to start up. Be cautious when
            # lowering this value to avoid Pod death during startup.
            initialDelaySeconds: 200
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /help
              port: {{ .Values.readinessPort }}
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: gitlab-data
            mountPath: /etc/gitlab
            subPath: config
          - name: gitlab-data
            mountPath: /var/opt/gitlab
            subPath: data
          - name: gitlab-data
            mountPath: /var/log/gitlab
            subPath: logs
      volumes:
        - name: gitlab-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.gitlab.existingClaim }}{{ .Values.persistence.gitlab.existingClaim }}{{- else }}{{ template "gitlab.fullname" . }}-gitlab{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
