apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitlab.fullname" . }}-ssh
  labels:
    app.kubernetes.io/name: {{ include "gitlab.name" . }}
    helm.sh/chart: {{ include "gitlab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.ssh.type }}
  ports:
    - name: ssh
      port: {{ .Values.service.ssh.port | int }}
      {{- if  .Values.service.ssh.nodePort }}
      nodePort: {{ .Values.service.ssh.nodePort }}
      {{- end }}
      targetPort: ssh
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "gitlab.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
