apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitlab.fullname" . }}-http
  labels:
    app.kubernetes.io/name: {{ include "gitlab.name" . }}
    helm.sh/chart: {{ include "gitlab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - name: http
      port: {{ .Values.service.http.port | int }}
      {{- if  .Values.service.http.nodePort }}
      nodePort: {{ .Values.service.http.nodePort }}
      {{- end }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "gitlab.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
