apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-{{ template "gitlab.fullname" . }}-ssh
  labels:
    app.kubernetes.io/name: {{ include "gitlab.name" . }}
    helm.sh/chart: {{ include "gitlab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{ .Values.service.ssh.externalPort }}: {{ .Release.Namespace }}/{{ template "gitlab.fullname" . }}:ssh
