apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "couchpotato.fullname" . }}-config
  labels:
    app: {{ template "couchpotato.name" . }}
    chart: {{ template "couchpotato.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/kubernetes/couchpotato-config
    server: 192.168.2.44
