apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchpotato-config
  labels:
    app: couchpotato
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/kubernetes/couchpotato-config
    server: 192.168.2.44
