apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchpotato-config
  labels:
    app: couchpotato
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


