# Default values for sickrage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: linuxserver/sickchill
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: true
  annotations:
    cert-manager.io/issuer: ca-kubernetes-issuer
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - sickchill.explorer
  tls:
    - secretName: sickchill-tls
      hosts:
        - sickchill.explorer

env:
  - name: TZ
    value: "Europe/Amsterdam"
  - name: PGID
    value: "10"
  - name: PUID
    value: "200"

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 800m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
