apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "bazarr.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "bazarr.name" . }}
    helm.sh/chart: {{ include "bazarr.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


