apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config
  labels:
    app: radarr
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/kubernetes/radarr-config
    server: san.explorer
