ingress:
  enabled: true
  annotations:
    # certmanager.k8s.io/issuer: ca-kubernetes-issuer
    # kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - radarr.renait.nl
  tls:
    - secretName: renait-prod
      hosts:
        - radarr.renait.nl

env:
  - name: TZ
    value: "Europe/Amsterdam"
  - name: PGID
    value: "10"
  - name: PUID
    value: "200"

resources:
  limits:
    cpu: 200m
    memory: 640Mi
  requests:
    cpu: 100m 
    memory: 256Mi

