apiVersion: v1
kind: PersistentVolume
metadata:
  name: sickrage-config
  labels:
    app: sickrage
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/kubernetes/sickrage-config
    server: 192.168.2.44
