apiVersion: v1
kind: PersistentVolume
metadata:
  name: sickrage-config
  labels:
    app: sickrage
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /fastdata/k8s/sickrage-config
    server: 172.16.0.10
