apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-realm: Authentication Required - monitoring
    ingress.kubernetes.io/auth-secret: basic-auth
    ingress.kubernetes.io/auth-type: basic
  name: kibana-logging
  namespace: kube-system
spec:
  rules:
  - host: k8s-kibana.explorer
    http:
      paths:
      - backend:
          serviceName: kibana-logging
          servicePort: 5601
        path: /
