apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncloud-mariadb
  labels:
    app: owncloud
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/kubernetes/owncloud/mariadb
    server: 172.16.0.10
