apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-config
spec:
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/kubernetes/mysql-config
    server: 192.168.2.44
