apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-v0
  labels:
    app: mysql
    version: v0
spec:
  replicas: 1
  selector:
    app: mysql
    version: v0
  template:
    metadata:
      labels:
        app: mysql
        version: v0
    spec: 
      securityContext:
        runAsUser: 27
        fsGroup: 27
      containers: 
      - name: mysql
        image: mariadb
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 6GRwVZINLRS6PMiZNVbO
        ports: 
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql
      - name: mysql-config
        persistentVolumeClaim:
          claimName: mysql-config

