apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mysql
spec:
  rules:
  - host: database.explorer
    tcp:
      port: 3306
      backend:
        serviceName: mysql
        servicePort: 3306
