apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-download
  labels:
    app: sabnzbd
spec:
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/download
    server: 172.16.0.10
