# Default values for sabnzbd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: linuxserver/sabnzbd
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/issuer: ca-kubernetes-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.org/proxy-connect-timeout: "15s"
    nginx.org/proxy-read-timeout: "10s"
    nginx.org/client-max-body-size: "8m"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - sabnzbd.explorer
  tls:
    - secretName: sabnzbd-tls
      hosts:
        - sabnzbd.explorer

env:
  - name: TZ
    value: "Europe/Amsterdam"
  - name: PGID
    value: "10"
  - name: PUID
    value: "200"

persistence:
  config:
    path: /fastdata/k8s/sabnzbd-config
    server: 172.16.0.10
  download:
    path: /data/download
    server: 172.16.0.10

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1000m
    memory: 756Mi
  requests:
    cpu: 200m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
