apiVersion: v1
kind: PersistentVolume
metadata:
  name: spotweb-mariadb
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/kubernetes/spotweb-mariadb
    server: 192.168.2.44
