apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-spotweb-mariadb-0
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/kubernetes/spotweb-mariadb2
    server: 172.16.0.10
