apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-spotweb-mariadb-0
  labels:
    app: spotweb
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /fastdata/k8s/spotweb-mariadb
    server: san.explorer
