apiVersion: v1
kind: PersistentVolume
metadata:
  name: chartmuseum
  labels:
    app: chartmuseum
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/k8s/chartmuseum
    server: san.explorer
