{{- if .Values.persistence.enabled -}}
{{- if not .Values.persistence.nextcloud.existingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "nextcloud.fullname" . }}-nextcloud
  labels:
    app.kubernetes.io: {{ include "nextcloud.name" . }}
    helm.sh/chart: {{ include "nextcloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.nextcloud.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.nextcloud.size | quote }}
{{- if .Values.persistence.nextcloud.storageClass }}
{{- if (eq "-" .Values.persistence.nextcloud.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.nextcloud.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}
