apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nextcloud.fullname" . }}
  labels:
    app.kubernetes.io: {{ include "nextcloud.name" . }}
    helm.sh/chart: {{ include "nextcloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.nextcloudPassword }}
  nextcloud-password: {{ .Values.nextcloudPassword | b64enc | quote }}
  {{ else }}
  nextcloud-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
