apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "plex.fullname" . }}
  labels:
    app: {{ template "plex.name" . }}
    chart: {{ template "plex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "plex.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "plex.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{ toYaml .Values.env | indent 12 }}
          ports:
            - name: http
              containerPort: 32400
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: plex-config
            mountPath: /config
          - name: plex-movies
            mountPath: /data/video
          - name: plex-pictures
            mountPath: /data/pictures
          - name: plex-transcode
            mountPath: /transcode
      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config
      - name: plex-movies
        persistentVolumeClaim:
          claimName: lib-movies
      - name: plex-pictures
        persistentVolumeClaim:
          claimName: lib-pictures
      - name: plex-transcode
        persistentVolumeClaim:
          claimName: transcode
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
