apiVersion: v1
kind: Service
metadata:
  name: {{ template "plex.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "plex.name" . }}
    helm.sh/chart: {{ include "plex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: pms
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: pms
{{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{.Values.service.nodePort}}
{{ end }}
    - name: http
      port: 80
      targetPort: pms
    - name: https
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/name: {{ include "plex.name" . }}
