#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: gitlab-data
#  labels:
#    app: gitlab
#spec:
#  capacity:
#    storage: 20Gi
#  accessModes:
#    - ReadWriteOnce
#  nfs:
#    path: /data/k8s/gitlab
#    server: san.explorer
#---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: san.explorer:3260
    iqn: iqn.2019-10.explorer.san:gitlab-data
    lun: 0
    fsType: 'ext4'
    readOnly: false
