apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-config
  labels:
    app: gitlab
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/k8s/gitlab/config
    server: san.explorer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data
  labels:
    app: gitlab
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/k8s/gitlab/data
    server: san.explorer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs
  labels:
    app: gitlab
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/k8s/gitlab/logs
    server: san.explorer
