apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data
  labels:
    app: gitlab
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/k8s/gitlab
    server: san.explorer
