# Default values for gitlab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gitlab/gitlab-ee
  tag: latest
  pullPolicy: IfNotPresent

service:
  http:
    type: ClusterIP
    port: 8080
    #nodePort: 30280
    # sometimes if is necesary to access through an external port i.e. http(s)://<dns-name>:<external-port>
    externalPort: 8280
    externalHost: gitlab.renait.nl
  ssh:
    type: NodePort
    port: 22
    nodePort: 30222
    ## if serving on a different external port used for determining the ssh url in the gui
    #externalPort: 8022
    #externalHost: git.example.com

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 15
    nginx.ingress.kubernetes.io/proxy-read-timeout: 600
  path: /
  hosts:
    - gitlab.renait.nl
  tls:
    - secretName: renait-prod
      hosts:
        - gitlab.renait.nl

env:
  GITLAB_OMNIBUS_CONFIG: |
    nginx['listen_port'] = 80;
    nginx['listen_https'] = false;
    external_url 'https://gitlab.renait.nl/';
    gitlab_rails['initial_root_password'] = 'geheim';
    gitlab_rails['initial_shared_runners_registration_token'] = 'token';
    gitlab_rails['gitlab_shell_ssh_port'] = 8999
    gitlab_rails['gitlab_signup_enabled'] = false;
    gitlab_rails['ldap_enabled'] = false ;

## livenessPort Port of liveness probe endpoint
livenessPort: http
## readinessPort Port of readiness probe endpoint
readinessPort: http

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 256m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
