apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "spotweb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "spotweb.name" . }}
    helm.sh/chart: {{ include "spotweb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "spotweb.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "spotweb.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: TZ
          value: "Europe/Amsterdam"
        - name: DB_HOST
          value: {{ .Release.Name }}-mariadb
        - name: DB_NAME
          value: {{ .Values.mariadb.db.name }}
        - name: DB_USER
          value: {{ .Values.mariadb.db.user }}
        - name: DB_PASS
          value: {{ .Values.mariadb.db.password }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}


