apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "spotweb.fullname" . }}
  labels:
    app: {{ template "spotweb.name" . }}
    chart: {{ template "spotweb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "spotweb.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "spotweb.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: mysql
        image: mariadb:10.2
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 6GRwVZINLRS6PMiZNVbO
        - name: MYSQL_USER
          value: spotweb
        - name: MYSQL_PASSWORD
          value: Zq59o7j21NWWg2cBXIdJ
        - name: MYSQL_DATABASE
          value: spotweb
        - name: TZ
          value: "Europe/Amsterdam"
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: TZ
          value: "Europe/Amsterdam"
        - name: DB_HOST
          value: "localhost"
        - name: DB_PASS
          value: "Zq59o7j21NWWg2cBXIdJ"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: spotweb-mariadb


