apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "spotweb.fullname" . }}-mariadb
  labels:
    app.kubernetes.io/name: {{ include "spotweb.name" . }}
    helm.sh/chart: {{ include "spotweb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
