apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "spotweb.fullname" . }}-mariadb
  labels:
    app: {{ template "spotweb.name" . }}
    chart: {{ template "spotweb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
