apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "spotweb.fullname" . }}-mariadb
  labels:
    app: {{ template "spotweb.name" . }}
    chart: {{ template "spotweb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/kubernetes/spotweb-mariadb
    server: 192.168.2.44
