apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-pgsql
  labels:
    app: openproject
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-data
  labels:
    app: openproject
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-logs
  labels:
    app: openproject
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
