apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-spotweb
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/kubernetes/mariadb-spotweb
    server: 192.168.2.44
