apiVersion: v1
kind: PersistentVolume
metadata:
  name: openkm-repository
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/kubernetes/openkm-repository
    server: 172.16.0.10
