apiVersion: v1
kind: ReplicationController
metadata:
  name: openkm-v0
  labels:
    app: openkm
    version: v0
spec:
  replicas: 1
  selector:
    app: openkm
    version: v0
  template:
    metadata:
      labels:
        app: openkm
        version: v0
    spec:
      containers:
      - name: openkm-mariadb
        image: mariadb:10.2
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 6GRwVZINLRS6PMiZNVbO
        - name: MYSQL_USER
          value: openkm
        - name: MYSQL_PASSWORD
          value: LcLWqeKRYaY8DMRu
        - name: MYSQL_DATABASE
          value: okmdb
        ports:
        - containerPort: 3306
          name: openkm-mariadb
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
      - name: openkm
        image: openkm/openkm
        env:
        - name: TZ
          value: "Europe/Amsterdam"
        resources:
          limits:
            cpu: "1000m"
            memory: "1768Mi"
          requests:
            cpu: "400m"
            memory: "512Mi"
        ports:
        - containerPort: 8080
          name: openkm
        volumeMounts:
        - name: openkm-repository
          mountPath: /opt/openkm/repository
        - name: openkm-config
          mountPath: /usr/local/tomcat/conf/server.xml
          subPath: server.xml
        - name: openkm-config
          mountPath: /usr/local/tomcat/OpenKM.cfg
          subPath: OpenKM.cfg
        - name: openkm-config
          mountPath: /usr/local/tomcat/OpenKM.xml
          subPath: OpenKM.xml
        imagePullPolicy: Always
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: openkm-mariadb	  
      - name: openkm-repository
        persistentVolumeClaim:
          claimName: openkm-repository
      - name: openkm-config
        configMap:
          name: openkm-config
