apiVersion: v1
kind: PersistentVolume
metadata:
  name: spotweb
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/kubernetes/spotweb
    server: 192.168.2.44
