apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-data
  labels:
    app: gogs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/k8s/gogs/data
    server: san.explorer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-pgsql
  labels:
    app: gogs
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/k8s/gogs/pgsql
    server: san.explorer
