apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncloud-mariadb
  labels:
    app: owncloud
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/kubernetes/owncloud/mariadb
    server: san.explorer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncloud-apache
  labels:
    app: owncloud
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/kubernetes/owncloud/apache
    server: san.explorer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncloud-data
  labels:
    app: owncloud
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/kubernetes/owncloud/data
    server: san.explorer
