apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "filerun.fullname" . }}
  labels:
    app: {{ template "filerun.name" . }}
    chart: {{ template "filerun.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "filerun.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "filerun.name" . }}
        release: {{ .Release.Name }}
    spec:
      hostname: filerun
      containers:
        - name: filerun-mariadb
          image: mariadb:10.2
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: 6GRwVZINLRS6PMiZNVbO
          - name: MYSQL_USER
            value: filerun
          - name: MYSQL_PASSWORD
            value: LcLWqeKRYaY8DMRu
          - name: MYSQL_DATABASE
            value: filerun
          - name: TZ
            value: "Europe/Amsterdam"
          ports:
          - containerPort: 3306
            name: filerun-mariadb
          volumeMounts:
          - name: mariadb-persistent-storage
            mountPath: /var/lib/mysql
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{ toYaml .Values.env | indent 12 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: filerun-html
            mountPath: /var/www/html
          - name: filerun-user-files
            mountPath: /user-files
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: filerun-mariadb      
      - name: filerun-html
        persistentVolumeClaim:
          claimName: filerun-html
      - name: filerun-user-files
        persistentVolumeClaim:
          claimName: filerun-user-files
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
