apiVersion: v1
kind: Service
metadata:
  name: {{ template "serviio.fullname" . }}-console
  labels:
    app: {{ template "serviio.name" . }}
    chart: {{ template "serviio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 23423
      targetPort: console
      protocol: TCP
      name: console
  selector:
    app: {{ template "serviio.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "serviio.fullname" . }}-browser
  labels:
    app: {{ template "serviio.name" . }}
    chart: {{ template "serviio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 23424
      targetPort: browser
      protocol: TCP
      name: browser
  selector:
    app: {{ template "serviio.name" . }}
    release: {{ .Release.Name }}
