apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "sabnzbd.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "sabnzbd.name" . }}
    helm.sh/chart: {{ include "sabnzbd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: {{ .Values.persistence.config.path }}
    server: {{ .Values.persistence.config.server }}
