apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "sabnzbd.fullname" . }}-config
  labels:
    app: {{ template "sabnzbd.name" . }}
    chart: {{ template "sabnzbd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: {{ .Values.persistence.config.path }}
    server: {{ .Values.persistence.config.server }}
