apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "sabnzbd.fullname" . }}-download
  labels:
    app.kubernetes.io: {{ include "sabnzbd.name" . }}
    helm.sh/chart: {{ include "sabnzbd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .Values.persistence.download.path }}
    server: {{ .Values.persistence.download.server }}
