apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "sabnzbd.fullname" . }}-download
  labels:
    app: {{ template "sabnzbd.name" . }}
    chart: {{ template "sabnzbd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Ti
