apiVersion: v1
kind: PersistentVolume
metadata:
  name: lib-pictures
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/media/pictures
    server: 172.16.0.10
