apiVersion: v1
kind: PersistentVolume
metadata:
  name: transcode
  labels:
    app: streamserver
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/kubernetes/transcode
    server: 172.16.0.10