apiVersion: v1
kind: PersistentVolume
metadata:
  name: transcode
  labels:
    app: streamserver
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /fastdata/k8s/transcode
    server: san.explorer
