apiVersion: v1
kind: PersistentVolume
metadata:
  name: lib-movies
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/media/video
    server: san.explorer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lib-pictures
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/media/pictures
    server: san.explorer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transcode
  labels:
    app: streamserver
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/k8s/transcode
    server: san.explorer
