apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lib-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lib-movies
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lib-pictures
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transcode
  labels:
    app: streamserver
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
