apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-mariadb
  labels:
    app: nextcloud
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/kubernetes/nextcloud/mariadb
    server: san.explorer
