apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus
  labels:
    app: nexus
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/kubernetes/nexus
    server: 172.16.0.10
