# Default values for nexus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  #repository: sonatype/nexus3
  #tag: 3.10.0
  repository: cavemandaveman/nexus
  tag: 3.12.1-01

# node labels for node selection
# nodeSelector:
#   cloud.google.com/gke-nodepool: default-pool

service:
  name: nexus
  type: ClusterIP
  externalPort: 8081
  internalPort: 8081
  readinessProbe:
    initialDelaySeconds: 180
    periodSeconds: 30
    failureThreshold: 6
  livenessProbe:
    initialDelaySeconds: 180
    periodSeconds: 30
  annotations: {}
  # foo.io/bar: "true"

ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - nexus.explorer
  annotations:
    kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: ca-kubernetes-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: "80m"
    nginx.org/proxy-connect-timeout: "30s"
    nginx.org/proxy-read-timeout: "20s"
    nginx.org/client-max-body-size: "80m"
  tls:
  # Secrets must be manually created in the namespace.
  - secretName: nexus-tls
    hosts:
      - nexus.explorer
## Configuration if choosing to host docker registry
docker:
  enabled: true
  # Used to enable a docker registry
  port: 5509
  host: docker.explorer
## Persist data to a persitent volume
persistence:
  enabled: true
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  existingClaim: "nexus"
  # storageClass: "-"
  # annotations:
  #  "helm.sh/resource-policy": keep
  accessMode: ReadWriteOnce
  size: 8Gi
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: "250m"
    memory: "4800Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

