appVersion: 16.0.5
description: A file sharing server that puts the control and security of your own
  data back into your hands.
engine: gotpl
home: https://nextcloud.com/
icon: https://github.com/nextcloud/docker/blob/master/logo.svg
keywords:
- nextcloud
- storage
- http
- web
- php
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: nextcloud
sources:
- https://github.com/nextcloud/docker
version: 1.4.0
