{{- if .Values.ingress.enabled }}
apiVersion: {{ required "A valid .Values.networkPolicyApiVersion entry required!" .Values.networkPolicyApiVersion }}
kind: Ingress
metadata:
  name: {{ template "openproject.fullname" . }}
  labels:
    app.kubernetes.io: {{ include "openproject.name" . }}
    helm.sh/chart: {{ include "openproject.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.openprojectHost }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "openproject.fullname" . }}
          servicePort: {{ .Values.ingress.servicePort }}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end }}
