{{- if .Values.persistence.enabled -}}
{{- if not .Values.persistence.logs.existingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "openproject.fullname" . }}-logs
  labels:
    app.kubernetes.io: {{ include "openproject.name" . }}
    helm.sh/chart: {{ include "nextcloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size | quote }}
{{- if .Values.persistence.logs.storageClass }}
{{- if (eq "-" .Values.persistence.logs.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.logs.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}
