apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openproject.fullname" . }}
  labels:
    app.kubernetes.io: {{ include "openproject.name" . }}
    helm.sh/chart: {{ include "openproject.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.openprojectPassword }}
  openproject-password: {{ .Values.openprojectPassword | b64enc | quote }}
  {{ else }}
  openproject-password: {{ randAlphaNum 30 | b64enc | quote }}
  {{ end }}
