apiVersion: v1
kind: Service
metadata:
  name: {{ template "openproject.fullname" . }}
  labels:
    app: {{ template "openproject.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  {{- if eq .Values.serviceType "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.openprojectLoadBalancerIP }}
  {{- end }}
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: {{ template "openproject.fullname" . }}
