apiVersion: v1
kind: Service
metadata:
  name: {{ template "openproject.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "openproject.name" . }}
    helm.sh/chart: {{ include "openproject.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "openproject.name" . }}
