apiVersion: v1
kind: Service
metadata:
  name: {{ template "openproject.fullname" . }}
  labels:
    app.kubernetes.io: {{ include "openproject.name" . }}
    helm.sh/chart: {{ include "openproject.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.serviceType }}
  {{- if eq .Values.serviceType "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.openprojectLoadBalancerIP }}
  {{- end }}
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "openproject.name" . }}
