apiVersion: v1
kind: PersistentVolume
metadata:
  name: openproject-pgsql
  labels:
    app: openproject
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/kubernetes/openproject/pgsql
    server: 172.16.0.10