# Default values for gitlab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gitlab/gitlab-ce
  tag: 11.7.5-ce.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  httpPort: 80
  sshPort: 22

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/issuer: ca-kubernetes-issuer
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - gitlab.explorer
  tls:
    - secretName: gitlab-tls
      hosts:
        - gitlab.explorer

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}
