apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-prometheus-db-alertmanager
  namespace: monitoring
  labels:
    app: kube-prometheus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /fastdata/k8s/monitoring/alertmanager
    server: san.explorer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-prometheus-db-prometheus
  namespace: monitoring
  labels:
    app: kube-prometheus
spec:
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /fastdata/k8s/monitoring/prometheus
    server: san.explorer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-prometheus-grafana
  namespace: monitoring
  labels:
    app: kube-prometheus
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /fastdata/k8s/monitoring/grafana
    server: san.explorer
